services:
  - type: web
    name: obit-engine
    env: node
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_DB
        value: obituary_api
